### ISSUE TITLE
Include MAC Address EEPROM

### ISSUE THREAD

**Issue by henrique-silva** [lnls-dig/rffe-uc-hw#10]
On MBED board, the MAC address is retrieved by a semihost call to the other controller on the board (the one that implements the filesystems), as explained [here](https://os.mbed.com/forum/mbed/post/4680/). Since we don't have this controller on our project, we need a different way to generate a valid MAC Address.

We can use the common [Microchip 24AAxx EEPROMs](https://www.microchip.com/design-centers/memory/serial-eeprom/getting-started/with-mac-address-chips), which are also used in the AFC board.

**Comment by aylons** [comment]
Tested and functional
