### ISSUE TITLE
EEPROM and FeRAM chips have the same slave address

### ISSUE THREAD

**Issue by henrique-silva** [lnls-dig/rffe-uc-hw#13]
Both these chips have the slave address defined as `0b1010xxx`. The EEPROM ignores the last 3 bits, but the FeRAM uses them as the most significant bits of the internal address register.
We can control which one we'll write using the WP bit of the FeRAM, but we can't be sure which one will respond to a read command, since both will only acknowledge the upper 4 bits of the slave address.

**Comment by augustofg** [comment]
To solve this I propose moving the 24AA02E48 EEPROM to the I2C0 bus (same of the CDCE906PW PLL). Both devices addresses differ in the first 4 bits so it should work fine.
