### ISSUE TITLE
LED pins on PHY chip must be configured via pull resistors

### ISSUE THREAD

**Issue by henrique-silva** [lnls-dig/rffe-uc-hw#6]
According to the PHYTER DP83848J [datasheet](http://www.ti.com/lit/ds/symlink/dp83848j.pdf) page 30, the LEDs that are driven by the PHY (LED_LINK and LED_SPEED) must be configured via pull-up or down resistors to act as a active high/low driver.

For our hardware, since the [RFFE controller board](https://github.com/lnls-dig/rffe-hw) uses common cathode configurations for the ethernet connector LEDs, we need the PHY to be a active-high driver, i.e., there must be a 2k2 pull-down resistor on the LED pins.

These pins don't need to be routed to the LPC1768, since it can't configure the PHY LED drivers, according to this information on the datasheet:

> AN0 (LED_LINK) AN1(LED_SPEED):
> The value on these pins are set by connecting them to GND (0) or VCC (1) through 2.2-k Ω resistors.
> These pins should NEVER be connected directly to GND or VCC.

The Auto-negotiation function of these pins is irrelevant. The LPC firmware overrides this option writing  the needed information directly on PHY registers.

**Comment by aylons** [comment]
Done in v1.1
